# Generated by Django 6.0.4 on 2026-04-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('monthly_target', models.IntegerField(default=0, help_text='Set the monthly new user target for this branch')),
            ],
            options={
                'verbose_name': 'Branch',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal identifier for the issue type', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly name shown in dropdowns', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this issue type is available for selection')),
                ('sort_order', models.IntegerField(default=0, help_text='Order in which this issue type appears in lists')),
            ],
            options={
                'verbose_name': 'Issue Type',
                'verbose_name_plural': 'Issue Types',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PanelBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='FRC CMS & TICKETS', max_length=120)),
                ('brand_subtitle', models.CharField(default='ADMIN PANEL', max_length=120)),
                ('logo_icon', models.CharField(default='⚡', max_length=10)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panel Brand Setting',
                'verbose_name_plural': 'Panel Brand Settings',
            },
        ),
        migrations.CreateModel(
            name='PartnerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedByOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Received By Option',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technician',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('sn', models.AutoField(help_text='Auto-incrementing serial number', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date when the ticket was created/occurred')),
                ('user_name', models.CharField(help_text='Name of the customer who raised the ticket', max_length=200)),
                ('partner_user_name', models.CharField(blank=True, help_text='End-user name for partner tickets', max_length=200, null=True)),
                ('customer_id', models.CharField(help_text='Unique identifier for the customer', max_length=100)),
                ('cell_no', models.CharField(help_text='Contact phone number for the customer', max_length=20)),
                ('issue', models.CharField(help_text='Type/category of the issue', max_length=100)),
                ('received_by', models.CharField(help_text='Who initially received the ticket', max_length=100)),
                ('time', models.TimeField(blank=True, help_text='Time when the ticket was created', null=True)),
                ('technician_name', models.CharField(blank=True, help_text='Assigned technician for resolution', max_length=100, null=True)),
                ('technician_assigned_at', models.DateTimeField(blank=True, help_text='Timestamp when technician was assigned', null=True)),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending'), ('TIME TAKEN', 'Time Taken'), ('No Response', 'No Response')], default='PENDING', help_text='Current status of the ticket', max_length=50)),
                ('solved_at', models.DateTimeField(blank=True, help_text='Timestamp when ticket was marked as solved', null=True)),
                ('forwarded_to', models.CharField(blank=True, help_text='Person/department the ticket was forwarded to', max_length=100, null=True)),
                ('forwarded_at', models.DateTimeField(blank=True, help_text='Timestamp when ticket was forwarded', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about the ticket', null=True)),
                ('is_partner', models.BooleanField(default=False, help_text='Indicates if this is a partner ticket')),
                ('is_new_user', models.BooleanField(default=False, help_text='Indicates if this solved ticket added a new user')),
                ('new_user_id', models.CharField(blank=True, help_text='New user/customer identifier created after solving', max_length=100, null=True)),
                ('branch', models.CharField(default='Head Quarter, Sirajganj', help_text='Branch location where the ticket originated', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date', 'status'], name='tickets_tic_date_edfb56_idx'), models.Index(fields=['customer_id'], name='tickets_tic_custome_c66646_idx'), models.Index(fields=['cell_no'], name='tickets_tic_cell_no_9bc72e_idx'), models.Index(fields=['technician_name'], name='tickets_tic_technic_b77a9e_idx'), models.Index(fields=['branch'], name='tickets_tic_branch_304937_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending'), ('TIME TAKEN', 'Time Taken'), ('No Response', 'No Response')], max_length=50)),
                ('remark', models.TextField()),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_remarks', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
