# Generated by Django 6.0.4 on 2026-04-28 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Branch',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedByOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Received By Option',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technician',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PanelBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='FRC CMS & TICKETS', max_length=120)),
                ('brand_subtitle', models.CharField(default='ADMIN PANEL', max_length=120)),
                ('logo_icon', models.CharField(default='⚡', max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Panel Brand Setting',
                'verbose_name_plural': 'Panel Brand Settings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('sn', models.AutoField(help_text='Auto-incrementing serial number', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date when the ticket was created/occurred')),
                ('user_name', models.CharField(help_text='Name of the customer who raised the ticket', max_length=200)),
                ('customer_id', models.CharField(help_text='Unique identifier for the customer', max_length=100)),
                ('cell_no', models.CharField(help_text='Contact phone number for the customer', max_length=20)),
                ('issue', models.CharField(help_text='Type/category of the issue', max_length=100)),
                ('received_by', models.CharField(help_text='Who initially received the ticket', max_length=100)),
                ('time', models.TimeField(blank=True, help_text='Time when the ticket was created', null=True)),
                ('technician_name', models.CharField(blank=True, help_text='Assigned technician for resolution', max_length=100, null=True)),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending'), ('TIME TAKEN', 'Time Taken'), ('No Response', 'No Response')], default='PENDING', help_text='Current status of the ticket', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about the ticket', null=True)),
                ('branch', models.CharField(default='Head Quarter, Sirajganj', help_text='Branch location where the ticket originated', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('forwarded_to', models.CharField(blank=True, help_text='Person/department the ticket was forwarded to', max_length=100, null=True)),
                ('solved_at', models.DateTimeField(blank=True, help_text='Timestamp when ticket was marked as solved', null=True)),
                ('technician_assigned_at', models.DateTimeField(blank=True, help_text='Timestamp when technician was assigned', null=True)),
                ('forwarded_at', models.DateTimeField(blank=True, help_text='Timestamp when ticket was forwarded', null=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending'), ('TIME TAKEN', 'Time Taken'), ('No Response', 'No Response')], max_length=50)),
                ('remark', models.TextField()),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_remarks', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal identifier for the issue type', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly name shown in dropdowns', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this issue type is available for selection')),
                ('sort_order', models.IntegerField(default=0, help_text='Order in which this issue type appears in lists')),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
                'verbose_name': 'Issue Type',
                'verbose_name_plural': 'Issue Types',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date', 'status'], name='tickets_tic_date_edfb56_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer_id'], name='tickets_tic_custome_c66646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cell_no'], name='tickets_tic_cell_no_9bc72e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['technician_name'], name='tickets_tic_technic_b77a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['branch'], name='tickets_tic_branch_304937_idx'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='Indicates if this is a partner ticket'),
        ),
        migrations.CreateModel(
            name='BranchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('monthly_user_target', models.PositiveIntegerField(default=0)),
                ('yearly_user_target', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_targets', to='tickets.branchoption')),
            ],
            options={
                'verbose_name': 'Branch Target',
                'verbose_name_plural': 'Branch Targets',
                'ordering': ['-year', '-month', 'branch__display_name'],
                'indexes': [models.Index(fields=['year', 'month'], name='tickets_bra_year_739c72_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'month', 'year'), name='unique_branch_target_period')],
            },
        ),
        migrations.CreateModel(
            name='DailyUserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_users_added', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_user_entries', to='tickets.branchoption')),
            ],
            options={
                'verbose_name': 'Daily User Entry',
                'verbose_name_plural': 'Daily User Entries',
                'ordering': ['-date', 'branch__display_name'],
                'indexes': [models.Index(fields=['date'], name='tickets_dai_date_692e17_idx'), models.Index(fields=['branch', 'date'], name='tickets_dai_branch__9b31d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_daily_user_entry')],
            },
        ),
        migrations.RenameIndex(
            model_name='branchtarget',
            new_name='tickets_bra_year_4d7cd0_idx',
            old_name='tickets_bra_year_739c72_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyuserentry',
            new_name='tickets_dai_date_8d3c05_idx',
            old_name='tickets_dai_date_692e17_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyuserentry',
            new_name='tickets_dai_branch__e91eeb_idx',
            old_name='tickets_dai_branch__9b31d8_idx',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_new_user',
            field=models.BooleanField(default=False, help_text='Indicates if this solved ticket added a new user'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='new_user_id',
            field=models.CharField(blank=True, help_text='New user/customer identifier created after solving', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DailyUserEntry',
        ),
        migrations.DeleteModel(
            name='BranchTarget',
        ),
        migrations.AddField(
            model_name='branchoption',
            name='monthly_target',
            field=models.IntegerField(default=0, help_text='Set the monthly new user target for this branch'),
        ),
        migrations.CreateModel(
            name='PartnerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='partner_user_name',
            field=models.CharField(blank=True, help_text='End-user name for partner tickets', max_length=200, null=True),
        ),
    ]
