# Generated by Django 6.0.4 on 2026-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_branchoption_issuetype_receivedbyoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='FRC CMS & TICKETS', max_length=120)),
                ('brand_subtitle', models.CharField(default='ADMIN PANEL', max_length=120)),
                ('logo_icon', models.CharField(default='⚡', max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panel Brand Setting',
                'verbose_name_plural': 'Panel Brand Settings',
            },
        ),
    ]
