# Generated by Django 6.0.4 on 2026-04-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_panelbrandsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelbrandsettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
