# Generated by Django 6.0.4 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_panelbrandsettings_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='forwarded_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='technician_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
