# Generated by Django 6.0.4 on 2026-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_assignment_and_forwarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
