# Generated by Django 6.0.4 on 2026-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_add_forwarded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuetype',
            options={'ordering': ['sort_order', 'display_name'], 'verbose_name': 'Issue Type', 'verbose_name_plural': 'Issue Types'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='display_name',
            field=models.CharField(help_text='User-friendly name shown in dropdowns', max_length=100),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this issue type is available for selection'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='name',
            field=models.CharField(help_text='Internal identifier for the issue type', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order in which this issue type appears in lists'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.CharField(default='Head Quarter, Sirajganj', help_text='Branch location where the ticket originated', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cell_no',
            field=models.CharField(help_text='Contact phone number for the customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_id',
            field=models.CharField(help_text='Unique identifier for the customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(help_text='Date when the ticket was created/occurred'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when ticket was forwarded', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forwarded_to',
            field=models.CharField(blank=True, help_text='Person/department the ticket was forwarded to', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(help_text='Type/category of the issue', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='received_by',
            field=models.CharField(help_text='Who initially received the ticket', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes about the ticket', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sn',
            field=models.AutoField(help_text='Auto-incrementing serial number', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when ticket was marked as solved', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending'), ('TIME TAKEN', 'Time Taken'), ('No Response', 'No Response')], default='PENDING', help_text='Current status of the ticket', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='technician_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when technician was assigned', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='technician_name',
            field=models.CharField(blank=True, help_text='Assigned technician for resolution', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(blank=True, help_text='Time when the ticket was created', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(help_text='Name of the customer who raised the ticket', max_length=200),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date', 'status'], name='tickets_tic_date_edfb56_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer_id'], name='tickets_tic_custome_c66646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cell_no'], name='tickets_tic_cell_no_9bc72e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['technician_name'], name='tickets_tic_technic_b77a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['branch'], name='tickets_tic_branch_304937_idx'),
        ),
    ]
