# Generated by Django 6.0.4 on 2026-04-21 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending'), ('TIME TAKEN', 'Time Taken'), ('No Response', 'No Response')], max_length=50)),
                ('remark', models.TextField()),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_remarks', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
