# Generated by Django 6.0.4 on 2026-04-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_indexes'),
        ('tickets', '0008_ticketremark'),
    ]

    operations = [
    ]
