# Generated by Django 6.0.4 on 2026-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_merge_0007_add_indexes_0008_ticketremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='Indicates if this is a partner ticket'),
        ),
    ]
