# Generated by Django 6.0.4 on 2026-04-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_branch_target_daily_user_entry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branchtarget',
            new_name='tickets_bra_year_4d7cd0_idx',
            old_name='tickets_bra_year_739c72_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyuserentry',
            new_name='tickets_dai_date_8d3c05_idx',
            old_name='tickets_dai_date_692e17_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyuserentry',
            new_name='tickets_dai_branch__e91eeb_idx',
            old_name='tickets_dai_branch__9b31d8_idx',
        ),
    ]
