# Generated by Django 6.0.4 on 2026-04-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_branch_tracking_add_ticket_new_user_fields'),
        ('tickets', '0012_sync_new_user_monitoring_indexes'),
    ]

    operations = [
    ]
