# Generated by Django 6.0.4 on 2026-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_merge_20260425_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoption',
            name='monthly_target',
            field=models.IntegerField(default=0, help_text='Set the monthly new user target for this branch'),
        ),
    ]
