# Generated by Django 6.0.4 on 2026-04-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_branchoption_monthly_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
