# Generated by Django 6.0.4 on 2026-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_partneroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='partner_user_name',
            field=models.CharField(blank=True, help_text='End-user name for partner tickets', max_length=200, null=True),
        ),
    ]
